<a href="https://colab.research.google.com/github/Pongpang-2102/Data-Mining-and-Machine-Learning_KDAI-Project/blob/main/HW1_KDAI_DM%26ML_IRIS_Classification_Puriwat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Author : Puriwat Sangrawee
- Student ID : 65056071


# Using Neuron Network for IRIS Classification

## 1. Prepare Environment

In [21]:
# Importing Packages
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn import datasets

The Iris dataset has 150 observations or Rows and 5 atttibutes or Columns of Iris Flowers.

First four columns are - **Sepal Length, Sepal Width , Petal Length, Petal Width**, all are in cm.


---


The Last column is containing the Classes - **['setosa' 'versicolor' 'virginica']**


---


As we are loading the dataset from sklearn, the dataset is already pre-processed.

**So, the Classes are - [ 0 , 1 , 2 ] instead of ['setosa' 'versicolor' 'virginica'].**

## 2. Loading Dataset

In [45]:
# Loading Dataset
data = datasets.load_iris()
print(data)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [46]:
# labelling a target
x = data.data
y = data.target
z = data.target_names
print(data.feature_names)
print(x[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[5.1 3.5 1.4 0.2]


## 3. Splitting Data

In [28]:
# Split Dataset
from sklearn.model_selection import train_test_split
x_train, x_test,  y_train, y_test = train_test_split(x, y, test_size=50)

In [47]:
# Data Shape
print(x_train.shape)
print(x_test.shape)

(100, 4)
(50, 4)


## 4. Modeling

In [48]:
# Building the Model
model= Sequential()

# specify neuron in first hidden layer = 100
model.add(Dense(100,input_shape=(4,), activation="relu"))

# the output should be categorized to be 3 classes 
model.add(Dense(3, activation='softmax'))

In [49]:
# Compile the Model
model.compile(optimizer= "rmsprop", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [50]:
# Fit the Model
model.fit(x_train,y_train, epochs=200 , batch_size = 5 , validation_split = 0.2)

Epoch 1/200
16/16 [==============================] - 1s 15ms/step - loss: 1.0402 - accuracy: 0.4250 - val_loss: 0.9167 - val_accuracy: 0.6000
Epoch 2/200
16/16 [==============================] - 0s 4ms/step - loss: 0.8266 - accuracy: 0.6625 - val_loss: 0.8194 - val_accuracy: 0.6000
Epoch 3/200
16/16 [==============================] - 0s 5ms/step - loss: 0.7298 - accuracy: 0.7000 - val_loss: 0.7217 - val_accuracy: 0.6000
Epoch 4/200
16/16 [==============================] - 0s 5ms/step - loss: 0.6485 - accuracy: 0.7375 - val_loss: 0.7044 - val_accuracy: 0.6000
Epoch 5/200
16/16 [==============================] - 0s 5ms/step - loss: 0.5911 - accuracy: 0.7000 - val_loss: 0.6212 - val_accuracy: 0.7500
Epoch 6/200
16/16 [==============================] - 0s 5ms/step - loss: 0.5481 - accuracy: 0.8250 - val_loss: 0.6214 - val_accuracy: 0.6000
Epoch 7/200
16/16 [==============================] - 0s 6ms/step - loss: 0.5071 - accuracy: 0.7625 - val_loss: 0.6469 - val_accuracy: 0.6000
Epoch 8/200


## 5. Evaluation & Prediction

In [51]:
# Evaluate the Model
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 7ms/step - loss: 0.1198 - accuracy: 0.9600


[0.11977329105138779, 0.9599999785423279]

In [52]:
# Predict for the first 25 Observations
pred=model.predict(x_test[:])
print(pred)

2/2 [==============================] - 0s 9ms/step
[[9.52372958e-10 2.09051953e-03 9.97909546e-01]
 [4.50371565e-13 3.96883615e-06 9.99996006e-01]
 [1.55487803e-10 4.23630263e-04 9.99576390e-01]
 [4.53107246e-10 1.41192670e-03 9.98587966e-01]
 [1.95160592e-05 9.98320758e-01 1.65964593e-03]
 [9.99897420e-01 1.02568083e-04 1.04008871e-17]
 [9.99998510e-01 1.47946150e-06 8.33130870e-22]
 [9.99931633e-01 6.82781611e-05 8.84953884e-18]
 [9.99839067e-01 1.60886935e-04 5.94344887e-17]
 [2.62202586e-12 2.44119146e-05 9.99975502e-01]
 [7.35921046e-12 1.07977603e-05 9.99989092e-01]
 [3.17796703e-16 1.15291115e-07 9.99999821e-01]
 [9.99992311e-01 7.59566092e-06 3.54401252e-21]
 [1.62425615e-10 2.27982222e-04 9.99772072e-01]
 [9.99814749e-01 1.85342011e-04 3.88864025e-17]
 [1.50180424e-09 3.50493193e-03 9.96495008e-01]
 [1.37586885e-05 8.67894173e-01 1.32092088e-01]
 [4.91936749e-04 9.99499381e-01 8.61002445e-06]
 [9.99948204e-01 5.17655280e-05 1.18743886e-18]
 [9.99992192e-01 7.73916599e-06 4.726

In [53]:
p=np.argmax(pred, axis=1)
print(p)
print(y_test[:])

[2 2 2 2 1 0 0 0 0 2 2 2 0 2 0 2 1 1 0 0 2 2 0 1 0 0 1 1 1 1 2 1 1 1 1 0 2
 0 2 2 2 1 2 0 1 2 1 0 1 2]
[2 2 2 2 1 0 0 0 0 2 2 2 0 2 0 2 1 1 0 0 2 2 0 1 0 0 1 1 1 1 2 1 1 1 1 0 2
 0 2 2 2 1 1 0 1 1 1 0 1 2]


In [54]:
# Prediction Result
for i in p:
  print("Predicted-Class: {},   Name: {}".format(i,z[i]))

Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 0,   Name: setosa
Predicted-Class: 0,   Name: setosa
Predicted-Class: 0,   Name: setosa
Predicted-Class: 0,   Name: setosa
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 0,   Name: setosa
Predicted-Class: 2,   Name: virginica
Predicted-Class: 0,   Name: setosa
Predicted-Class: 2,   Name: virginica
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 0,   Name: setosa
Predicted-Class: 0,   Name: setosa
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 0,   Name: setosa
Predicted-Class: 1,   Name: versicolor
Predicted-Class: 0,   Name: setosa
Predicted-Class: 0,   Name: setosa
Predicted-Class: 1,   Name: versicolor
Pr